config/routes.rb
Rails.application.routes.draw do
  resources :tweets  
  ActiveAdmin.routes(self)
  devise_for :users
 as :user do 
 	get "signin" => "devise/sessions#new"
 	delete "signout" => 'devise/sessions#destroy'
 	get 'signup' => 'devise/registrations#new'
 end
  root 'pages#home'
get 'about' => 'pages#about'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_authorization.rb
class AdminAuthorization < ActiveAdmin::AuthorizationAdapter

  def authorized?(action, subject =nil)
  	user && user.admin?
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
	belongs_to :user

	validates :user, presence: true
	validates :content, presence: true, length: { maximum: 140}
end

app/models/user.rb
 class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, 
  :rememberable, :trackable, :validatable

  has_many :tweets
  has_many :items

  validates :username, presence: true, uniqueness: true, length: {minimum: 6}
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
 before_action :configure_permitted_parameters, if: :devise_controller?

  def access_denied(exception)
  	redirect_to root_path, alert: exception.message
  end

   protected

  def configure_permitted_parameters
  	devise_parameter_sanitizer.permit(:sign_up, keys: [:username, :name])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
    before_action :authenticate_user!, except: [:index, :show]

  # GET /tweets
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = current_user.tweets.new
  end

  # GET /tweets/1/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
  end

  # POST /tweets
  def create
   @tweet = current_user.tweets.new(tweet_params[:id])
    if @tweet.save
      redirect_to @tweet, notice: 'Tweet was successfully created.'
    else
      render :new 
    end
  end

  # PATCH/PUT /tweets/1
  def update
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.update(tweet_params)
      redirect_to tweet_url, notice: 'Tweet was successfully updated.'
    else
      render :edit
    end
  end


  # DELETE /tweets/1
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    @tweet.destroy
    redirect_to tweets_url, notice: 'Tweet was ABOLISHED.'
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    def tweet_params
      params.require(:tweet).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MY AWESOME 'SITE</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <!-- Navigation Bar -->
    <nav class="navbar navbar-inverse navbar-toggleable-sm bg-inverse"> navbar-inverse bg-inverse">
      <div class="container">
        <%= link_to "One Month Rails", root_path, class: "navbar-brand" %>
        <ul class="navbar-nav">
          <li class="nav-item"><%= link_to "Home", root_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "About", about_path, class: "nav-link" %></li>
          <li class="nav-item"><%= link_to "Contact", "#", class: "nav-link" %></li>
          <% if user_signed_in? %> 
          <li class="nav-item float-right"><%= link_to "Log out", signout_path, method: :delete, class: "nav-link" %></li>
          <% else %>
          <li class="nav-item float-right"><%= link_to "Sign up", signup_path, class: "nav-link btn btn-primary" %></li>
          <li class="nav-item float-right"><%= link_to "Sign in", signin_path, class: "nav-link" %></li>
          
          
          
          <% end %>

        </ul>
      </div>
    </nav>

    <!-- flash messges-->
    <% flash.each do |name, message| %>
    <%= content_tag(:div, message, class: "alert alert-info #{name}") %>
    <% end %>

    <!-- Page Content -->
    <%= yield %>
    
    <!-- Footer -->
    <footer class="small text-muted">
      <div class="container">
        <hr>
        <center>
          <p>© 2016 One Month</p>
        </center>
      </div>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<div class="jumbotron jumbotron-about">
    <div class="container">
        <h1>About us</h1>
        <p>This is the sample project I built for <a href="https://onemonthrails.com">One Month Rails</a>.<br /><b><em>
        this project was made through blood sweat and tears</em></b></p>
    </div>
</div>

app/views/pages/contact.html.erb
<div class="jumbotron jumbotron-about">
    <div class="container">
<h1>Contact</h1>
<p>email address: reneeedmonds7@gmail.com</p>
<p>ph number: 970 3114</p>

app/views/pages/home.html.erb
 <% if user_signed_in? %>
    <div class="jumbotron jumbotron-home">
        <div class="container">
        <h1>Welcome back!</h1>
        </div>
        </div>
<% else %>
    <div class="jumbotron jumbotron-home">
        <div class="container">

            <h1>Welcome to my website!</h1>
            <p>THIS IS MY WEBSITE. i do not know what it is for but it is the website i am making with one month rails</p>
        <%= link_to "Learn more »", "#", class: "btn btn-primary btn-lg" %> 
    </div>
</div>
 
<div class="container">
    <div class="row">
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
        <div class="col-md-4">
            <h2>Heading</h2>
            <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. </p>
            <p><%= link_to "View details", "#", class: "btn btn-secondary" %></p>
        </div>
    </div>
</div>
 <% end %>

app/views/tweets/_form.html.erb
<%= form_for(tweet) do |f| %>
  <% if tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="form-group">
  <% f.label :user_id %>
  <%= f.text_field :user_id, class: "form-control" %>
</div>

</div class="form-group">
  <%= f.label :content %>
  <%= f.text_area :content, class: "form-control" %>
</div>

   
    <%= f.submit class: "btn btn-primary" %>
<% end %>

app/views/tweets/edit.html.erb
<div class="container"
	<h1>Editing Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Show', @tweet %> |
	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/index.html.erb
  <div class="container">

  <div class="row">
     <div class="col-md-4">
     <div class="card card-block"
     <h4 class="card-title">Your Account</h4>
  <p class="card-text"> <%= current_user.username %></p>

       </div>
    </div>
  <div class="col-md-8">
   <% if user_signed_in? %>
   <%= link_to 'New Tweet', new_tweet_path %>
    <% end %>
  <ul class="list-group">
       <% @tweets.each do |tweet| %>
<li class="list-group-item">
<%= link_to tweet do %>
   <h5 class="list-group-item-heading"><%= tweet.user.username.try(:id) %></td></h5>

      <p class="list-group-item-text"><%= tweet.content %></td></p>

         <p class="list-group-item-text"><%= link_to 'Show', tweet %></td></p>

           <% if tweet.user == current_user %>
         <p class="list-group-item-text"><%= link_to 'Edit', edit_tweet_path(tweet) %></td></p>
         
      <p class="list-group-item-text"><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td></p>
    <% end %>
   </li>
<% end %>
      <% end %>
         </ul>
       </div>
      </div>
    </div>

app/views/tweets/new.html.erb
	<h1>New Tweet</h1>

	<%= render 'form', tweet: @tweet %>

	<%= link_to 'Back', tweets_path %>
</div>

app/views/tweets/show.html.erb
<div class="container">
  <div class="row">
    <div class="offset-md-2 col-md-8">
      <div class="card card-block">
        <h4 class="card-title"><%= @tweet.user.username %></h4>
          <p class="card-text"><%= @tweet.content %></p>
        <% if @tweet.user == current_user %>
      <%= link_to 'Edit', edit_tweet_path(@tweet), class: "card-link" %>
    <%= link_to 'Delete', @tweet, method: :delete, class: "card-link" %>
  <% end %>
<%= link_to 'Back', tweets_path, class: "card_link" %>
     </div>
    </div>
  </div>
</div>